SET DATABASE SQL SYNTAX DB2 TRUE;
CREATE SCHEMA SMC AUTHORIZATION DBA;

CREATE TABLE SMC.SMC_PO_SUBCATEGORY
(
   PO_SUBCATEGORY_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_SUBCATEGORY varchar(100) NOT NULL,
   DESCRIPTION varchar(50),
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_PO_CATEGORY
(
   PO_CATEGORY_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_CATEGORY varchar(20) NOT NULL,
   DESCRIPTION varchar(30),
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_PO_CATEGORY_ASSOC
(
   PO_CATEGORY_ASSOC_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_CATEGORY_ID int NOT NULL,
   PO_SUBCATEGORY_ID int NOT NULL,
   ACTIVE char(1) DEFAULT '1' NOT NULL,
   MAKE_MODEL_YEAR_REQ char(1),
   VEHICLE_TYPE_REQ char(1),
   VEHICLE_SIZE_REQ char(1)
);

CREATE TABLE SMC.SMC_SHIP_THRU_LEAD
(
   LEAD_TIME_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_CATEGORY varchar(20) NOT NULL,
   OEM varchar(3),
   MODEL varchar(50),
   SHIP_THRU_UPFITTER varchar(50),
   DESTINATION_STATE varchar(2),
   LEAD_DAYS int NOT NULL,
   CREATED_BY       VARCHAR(50) NOT NULL,
   CREATED_DATE    TIMESTAMP   NOT NULL,
   MODIFIED_BY      VARCHAR(50)  NOT NULL,
   MODIFIED_DATE      TIMESTAMP   NOT NULL
);

CREATE TABLE SMC.SMC_HELP ( 
	HELP_ID 		int 		GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	USER_TYPE  		VARCHAR(6) 											 NOT NULL, 
	HELP_TEXT  		VARCHAR(32000)  									 NOT NULL
);

CREATE TABLE SMC.SMC_ALERT_HEADER ( 
	HEADER_ID 			int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	HEADER_KEY 			VARCHAR(25) 								 NOT NULL, 
	HEADER_NAME 		VARCHAR(50) 								 NOT NULL, 
	TAB_ID 				INTEGER 									 NOT NULL, 
	HELP_TEXT 			VARCHAR(100) 								 NULL , 
	DISPLAY_SEQUENCE    INTEGER 									 NOT NULL
);

CREATE TABLE SMC.SMC_ALERTS ( 
	ALERT_ID 			int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	ALERT_KEY 			VARCHAR(30) 									 NOT NULL , 
	ALERT_NAME 			VARCHAR(100) 									 NOT NULL , 
	TEMPLATE_ID 		INTEGER 		 								 NULL , 
	DISPLAY_SEQUENCE 	INTEGER  										 NULL , 
	HEADER_ID 			INTEGER 										 NOT NULL , 
	VISIBILITY_VENDOR	SMALLINT 										 NOT NULL , 
	VISIBILITY_PENSKE 	SMALLINT 										 NOT NULL , 
	ACTIONABLE 			SMALLINT 										 NOT NULL , 
	HELP_TEXT 			VARCHAR(255) 									 NULL , 
	MEASURE_VALUE		INTEGER  	 									 NULL , 
	COMPLIANCE_TEXT		VARCHAR(255)									 NULL
);

CREATE TABLE SMC.SMC_TAB_MASTER ( 
	TAB_ID 				int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	TAB_KEY 			VARCHAR(15) 									 NOT NULL , 
	TABNAME 			VARCHAR(100) 									 NOT NULL , 
	DISPLAY_SEQUENCE 	INTEGER 										 NOT NULL , 
	IMG_URL 			VARCHAR(150) 									 NULL , 
	TEMPLATE_ID 		INTEGER 										 NOT NULL , 
	DASHBOARD_TAB 		SMALLINT 											NOT NULL, 
	STATUS 				CHAR(1)  										 NOT NULL, 
	CREATED_BY 			VARCHAR(100) 									 NOT NULL , 
	CREATED_DATE 		TIMESTAMP 										 NOT NULL , 
	MODIFIED_BY 		VARCHAR(100) 									 NULL , 
	MODIFIED_DATE 		TIMESTAMP 										 NULL 
);

CREATE TABLE SMC.SMC_SEARCH_TEMPLATES ( 
	TEMPLATE_ID 		int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	TEMPLATE_KEY 		VARCHAR(25) 								 NOT NULL , 
	TEMPLATE_NAME 		VARCHAR(50) 								 NOT NULL , 
	DISPLAY_SEQUENCE 	SMALLINT									 NOT NULL , 
	VISIBILITY_VENDOR 	CHAR(1) 									 NULL , 
	VISIBILITY_PENSKE 	CHAR(1) 									 NULL , 
	STATUS 				CHAR(1) 									 NOT NULL, 
	CREATED_BY 			VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE		TIMESTAMP 									 NOT NULL , 
	MODIFIED_BY			VARCHAR(100) 								 NULL , 
	MODIFIED_DATE		TIMESTAMP 									 NULL
);

CREATE TABLE SMC.SMC_SECURITY_FUNCTION ( 
	SEC_FUNC_ID 		int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	NAME 				VARCHAR(50) 								 NOT NULL , 
	DESCRIPTION			VARCHAR(150) 								 NULL , 
	TAB_ID				INTEGER 									 NULL , 
	STATUS				CHAR(1) 									 NOT NULL, 
	CREATED_BY			VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE		TIMESTAMP 								  	 NOT NULL , 
	MODIFIED_BY			VARCHAR(100) 								 NULL , 
	MODIFIED_DATE		TIMESTAMP 									 NULL 
);

CREATE TABLE SMC.SMC_ROLE_SEC_FUNCTIONS ( 
	SEC_FUNC_ID 		INTEGER 									NOT NULL , 
	ROLE_ID 			INTEGER 									NOT NULL   
);

CREATE TABLE SMC.SMC_USER_MASTER ( 
	USER_ID 			int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	SSO 				VARCHAR(100) 								 NOT NULL , 
	GESSOUID			VARCHAR(100) 								 NOT NULL , 
	FIRST_NAME			VARCHAR(100) 								 NOT NULL , 
	LAST_NAME 			VARCHAR(100) 								 NOT NULL , 
	EMAIL				VARCHAR(100) 								 NOT NULL , 
	PHONE				VARCHAR(10) 								 NULL , 
	EXTENSION			VARCHAR(5) 									 NULL , 
	STATUS				CHAR(1) 									 NOT NULL , 
	TYPE_ID				INTEGER 									 NOT NULL , 
	DEPT_ID				INTEGER                             		 NOT NULL, 
	ROLE_ID				INTEGER 									 NOT NULL , 
	OEM 				VARCHAR(20) 								 NULL , 
	CREATED_BY			VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE		TIMESTAMP 									 NOT NULL , 
	MODIFIED_BY			VARCHAR(100) 								 NULL , 
	MODIFIED_DATE		TIMESTAMP 									 NULL , 
	ORG_ID 				INTEGER 									 NOT NULL , 
	OPTDLYEML 			VARCHAR(1) 			 						 NOT NULL 
);

CREATE TABLE SMC.SMC_VENDOR_MASTER ( 
	VENDOR_ID 				int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	CORP 					CHAR(4) 									 NOT NULL , 
	VENDOR_NUMBER			INTEGER 									 NOT NULL , 
	VENDOR_NAME				VARCHAR(100) 								 NOT NULL , 
	MFR						VARCHAR(10) 								 NULL , 
	NOTIFICATION_EXCEPTION 	CHAR(1) 									 NOT NULL , 
	ANNUAL_AGREEMENT 		CHAR(1) 									 NOT NULL , 
	PAYMENT_TERMS 			INTEGER 									 NULL , 
	ADDRESS1 				VARCHAR(100) 								 NOT NULL , 
	ADDRESS2 				VARCHAR(100) 								 NULL , 
	CITY 					VARCHAR(50) 								 NOT NULL , 
	STATE 					VARCHAR(50) 								 NOT NULL , 
	ZIP 					VARCHAR(15) 								 NULL , 
	STATUS					CHAR(1) 									 NOT NULL , 
	CREATED_BY 				VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE 			TIMESTAMP 									 NOT NULL , 
	MODIFIED_BY 			VARCHAR(100) 								 NULL , 
	MODIFIED_DATE 			TIMESTAMP 									 NULL , 
	PLANNING_ANALYST 		INTEGER 									 NULL , 
	SUPPLY_SPECIALIST 		INTEGER 									 NULL
);

CREATE TABLE SMC.SMC_ORG_VENDOR_ASSOC ( 
	ASSOCIATION_ID 			int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL ,
	ORG_ID 					INTEGER 									 NOT NULL , 
	VENDOR_ID 				INTEGER 									 NOT NULL 
);

CREATE TABLE SMC.SMC_USER_LOGIN ( 
	LOGIN_ID 				int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	SSO						VARCHAR(100) 								 NOT NULL , 
	SERVER_LOCATION 		VARCHAR(30) 								 NULL , 
	LOGIN_TIME 				TIMESTAMP 									 NOT NULL
);

CREATE TABLE SMC.SMC_VENDOR_FILTER ( 
	VENDOR_FILTER_ID 		int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	VENDOR_ID				INTEGER 									 NOT NULL , 
	USER_ID					INTEGER 									 NOT NULL , 
	IS_ACTIVE				INTEGER 									 NOT NULL
);

CREATE TABLE SMC.SMC_ORG_MASTER ( 
	ORG_ID 					int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	NAME 					VARCHAR(50) 								 NOT NULL , 
	DESCRIPTION 			VARCHAR(255) 								 NULL , 
	PARENT_ORG_ID			INTEGER 									 NULL , 
	CREATED_BY				VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE			TIMESTAMP  									 NOT NULL , 
	MODIFIED_BY				VARCHAR(100) 								 NULL , 
	MODIFIED_DATE			TIMESTAMP 									 NULL 
);

CREATE TABLE SMC.SMC_LOOKUP ( 
	LOOKUP_ID 				int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	LOOKUP_NAME				VARCHAR(50) 								 NOT NULL , 
	LOOKUP_VALUE			VARCHAR(500) 								 NOT NULL , 
	LOOKUP_DESC				VARCHAR(100) 								 NOT NULL , 
	LOOKUP_SEQ				SMALLINT 									 NULL , 
	LOOKUP_STATUS			CHAR(1) 									 NOT NULL , 
	CREATED_BY				VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE			TIMESTAMP 									 NULL , 
	MODIFIED_BY				VARCHAR(100) 								 NOT NULL , 
	MODIFIED_DATE			TIMESTAMP 									 NULL 
);

CREATE TABLE SMC.SMC_BUDDIES ( 
	SSO 					VARCHAR(10) 								 NOT NULL , 
	BUDDY_SSO				VARCHAR(10) 								 NOT NULL , 
	USER_DEPT				VARCHAR(20) 								 NOT NULL , 
	CREATED_BY				VARCHAR(10) 								 NOT NULL , 
	CREATED_DATE			TIMESTAMP 									 NULL , 
	SELECTION_TYPE			VARCHAR(20) 								 NULL
);

CREATE TABLE SMC.SMC_USER_DEPT ( 
	DEPT_ID 				int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	USER_DEPT				VARCHAR(20) 								 NOT NULL , 
	DESCRIPTION				VARCHAR(50) 								 NULL , 
	STATUS					CHAR(1) 									 DEFAULT 'A' , 
	CREATED_BY				VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE			TIMESTAMP 									 NOT NULL , 
	MODIFIED_BY				VARCHAR(100) 								 DEFAULT NULL , 
	MODIFIED_DATE			TIMESTAMP 									 DEFAULT NULL 
);

CREATE TABLE SMC.SMC_TERMS_AND_CONDITIONS ( 
	VERSION_NUMBER 			int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	START_DATE				DATE 										 NOT NULL , 
	END_DATE				DATE 										 NOT NULL , 
	TC_TEXT					CLOB(1048576) 								 NOT NULL , 
	TEXT_SIZE				DECIMAL(4, 2) 								 NOT NULL , 
	STATUS 					CHAR(1) 									 DEFAULT 'A' , 
	CREATED_BY				VARCHAR(100) 								 NOT NULL , 
	CREATED_DATE			TIMESTAMP 									 NOT NULL , 
	MODIFIED_BY				VARCHAR(100) 								 DEFAULT NULL , 
	MODIFIED_DATE			TIMESTAMP 									 DEFAULT NULL 
);
