SET DATABASE SQL SYNTAX DB2 TRUE;
CREATE SCHEMA SMC AUTHORIZATION DBA;

CREATE TABLE SMC.SMC_PO_SUBCATEGORY
(
   PO_SUBCATEGORY_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_SUBCATEGORY varchar(100) NOT NULL,
   DESCRIPTION varchar(50),
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_PO_CATEGORY
(
   PO_CATEGORY_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_CATEGORY varchar(20) NOT NULL,
   DESCRIPTION varchar(30),
   STATUS char(1) NOT NULL,
   CREATED_BY varchar(10) NOT NULL,
   CREATED_DATE timestamp NOT NULL,
   MODIFIED_BY varchar(10),
   MODIFIED_DATE timestamp
);

CREATE TABLE SMC.SMC_PO_CATEGORY_ASSOC
(
   PO_CATEGORY_ASSOC_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_CATEGORY_ID int NOT NULL,
   PO_SUBCATEGORY_ID int NOT NULL,
   ACTIVE char(1) DEFAULT '1' NOT NULL,
   MAKE_MODEL_YEAR_REQ char(1),
   VEHICLE_TYPE_REQ char(1),
   VEHICLE_SIZE_REQ char(1)
);

CREATE TABLE SMC.SMC_SHIP_THRU_LEAD
(
   LEAD_TIME_ID int GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   PO_CATEGORY varchar(20) NOT NULL,
   OEM varchar(3),
   MODEL varchar(50),
   SHIP_THRU_UPFITTER varchar(50),
   DESTINATION_STATE varchar(2),
   LEAD_DAYS int NOT NULL,
   CREATED_BY       VARCHAR(50) NOT NULL,
   CREATED_DATE    TIMESTAMP   NOT NULL,
   MODIFIED_BY      VARCHAR(50)  NOT NULL,
   MODIFIED_DATE      TIMESTAMP   NOT NULL
);