package com.penske.apps.buildmatrix.domain;

/**
 * This object represents all the selected Options for a single Order, that will
 * appear on a report generated by an admin user. These will be correlated to
 * the ReportResultOrderModel to form an Excel spreadsheet that will be
 * downloaded.
 */
public class ReportResultOptionModel
{
	/** The unique identifier for the order this option belongs to */
	private Integer orderId;
	/** The ID of the option group this option belongs to */
	private Integer optionGroupId;	
	/** The option human-readable name of the option group this option belongs to */
	private String optionGroupDescription;
	/** A human-readable description of this option */
	private String optionDescription;

	/** Null constructor - MyBatis only */
	protected ReportResultOptionModel() {}
	
	/** {@inheritDoc} */
	@Override
	public String toString()
	{
		return "{ReportResultOptionModel (Order " + orderId + ", Option Group " + optionGroupId + ")}";
	}
	
	//***** DEFAULT ACCESSORS *****//
	public Integer getOrderId()
	{
		return orderId;
	}

	public Integer getOptionGroupId()
	{
		return optionGroupId;
	}

	public String getOptionGroupDescription()
	{
		return optionGroupDescription;
	}

	public String getOptionDescription()
	{
		return optionDescription;
	}
}